### ISSUE TITLE
Redis needs a service?

### ISSUE THREAD

**Issue by atomantic** [kubernetes/examples#107]
I just setup redis in my cluster using this guide: https://github.com/kubernetes/examples/tree/master/staging/storage/redis#tl-dr

The only service this creates is the sentinel at port 26379.
So when connecting to redis via the application pods, should they be referecing redis-sentinel:26379, or should we be creating a second service like the following to use for our applications to connect to redis?

```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis
    role: service
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis
    role: master
```

**Comment by ahmetb** [comment]
I'm not familiar with the matter directly, but the example reads:

> In Redis, we will use a Kubernetes Service to provide a discoverable endpoints for the Redis sentinels in the cluster. From the sentinels Redis clients can find the master, and then the slaves and other relevant info for the cluster. This enables new members to join the cluster when failures occur.

Have you tried running the provided example and see it works?

**Comment by atomantic** [comment]
yeah, that only refers to the redis pods themselves finding the sentinel as a service.

I installed according to the instructions but couldn't get it to work as a redis source for the applications--connecting to the redis-sentinel on 26379 didn't do it.

I ended up switching to using ```help install stable/redis-ha``` with some custom configs and that did the trick.

**Comment by ahmetb** [comment]
@atomantic thanks for the insight, we should probably also deprecate this example in favor of the Helm chart.

**Comment by monotykamary** [comment]
The example supposes that the redis-master exists as a mortal pod. When it dies (and is gone forever), it will then do failover on existing replicas. This doesn't happen on the helm chart because the pod resurrects before the failover timeout:

```
$ kubectl delete pods redis-master-0
pod "redis-master-0" deleted

# wait until StatefulSet pod is up
$ cat /etc/passwd | redis-cli -h 172.30.206.66 -p 6379 -x set mypasswd
OK
```

Since the service only exposes for the redis-master pod, it is no different to a basic master-slave replication; albeit with a huge risk. In the event that the failover timeout is reached before the pod is resurrected, a redis-replica pod would be promoted to master and the original bootstrap redis-master pod would no longer be a master. The fixed service pointing to the redis-master pod will point to a read-only pod.

That said, there isn't a clean way (at least with this setup) to use Kubernetes services to point to the right master pod. Suppose we add the label to invite the replicas into the service:

```
     metadata:
       labels:
         name: redis
+        redis-node: "true"
         role: replica
     spec:
       containers:
```

The service will round-robin against the pods as expected:

```
$ cat /etc/passwd | redis-cli -h 172.30.206.66 -p 6379 -x set mypasswd
OK
$ cat /etc/passwd | redis-cli -h 172.30.206.66 -p 6379 -x set mypasswd
(error) READONLY You can't write against a read only slave.
$ cat /etc/passwd | redis-cli -h 172.30.206.66 -p 6379 -x set mypasswd
(error) READONLY You can't write against a read only slave.
$ cat /etc/passwd | redis-cli -h 172.30.206.66 -p 6379 -x set mypasswd
(error) READONLY You can't write against a read only slave.
$ cat /etc/passwd | redis-cli -h 172.30.206.66 -p 6379 -x set mypasswd
OK
$ cat /etc/passwd | redis-cli -h 172.30.206.66 -p 6379 -x set mypasswd
OK
```

**Comment by atomantic** [comment]
Thanks for the detailed response. That makes sense. Half of me is wondering if using the sentinel is excessive within kubernetes in the first place since kubernetes is resurrecting the master on fail and getting it into a CrashLoopBackOff state.

deleting the master pod as you show, enables kubernetes to recreate the master and the redis cluster is alive again (for about 4 hours in my case).

Interesting idea about just labeling them all and relying on retry logic... that could fix it up for the time being. I'm not entirely sure why the master is failing in the first place so that's still under investigation.
