### ISSUE TITLE
Clarification about container policy

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/examples#11]
I am reading this:

> Docker images are pre-built, and source is contained in a subfolder.
> Source is the Dockerfile and any custom files needed beyond the upstream app being packaged.
> Images are pushed to gcr.io/google-samples. Contact @jeffmendoza to have an image pushed
> Images are tagged with a version (not latest) that is referenced in the example config.

This has been a challenge in the past, since getting an update in takes way too long.  Are we going to implement a system to automatically push new containers?  Are we going to force all containers Dockerfiles to exist in this repo?

**Comment by ahmetb** [comment]
@chrislovecnm I was hoping to take a stab at this problem this quarter (Apr-June'17) but did not have enough time. I am postponing to the next quarter. Main challenges I observed while I was looking at this work:

(1) You need someone to update the image.
(2) I'm not sure community is okay with gcr.io. Is dockerhub/quay a better answer for the community needs?
(3) We're not sure who are the owners all the images in gcr.io/google-samples<sup>1</sup> are.
(4) We're not sure where are the sources/Dockerfiles of these images are either.
(5) Tagging policy of the existing images<sup>1</sup> is inconsistent. Some have :v1, some have :1.0, and some just do :latest.

It would be great if we can have an image builder all Kubernetes project can benefit. Primarily for the ones used in this directory, we should be able to _transparently_<sup>2</sup> build and push to a public registry. I reckon these builds would be done in a 

- automated (on code push), and
- periodical (to update the base images used in the images) fashion

If you have cycles to devote on this problem, I most certainly appreciate help and would love to help out if you want to do most of the work as well. Before doing this work, I am going to clean up the maintained examples at the root of this repository to be free of GCE/GKE/vendor-specific instructions as well.

We should be documenting the result of this work as a "sample image policy" in the `guidelines.md`. Until then, I can help with the publishing of new images to _gcr.io/google-samples_. (Maybe I should update Jeff's handle with mine since I'm likely to take over the maintenance responsibilities.)

-----
<sup>1</sup> `gcloud container images list --repository gcr.io/google-samples`
<sup>2</sup> Kubernetes community members should be able to see logs of a build, see build dates of each image, perhaps even kick off new builds

**Comment by chrislovecnm** [comment]
So not quite my question.  

Does an example in the repo have to use a Docker maintained in this repo?

Unfortunately, I do not have cycles to work on automating the building of containers.

**Comment by ahmetb** [comment]
(in my opinion–) If the image is a well-known and maintained one, or the source/Dockerfile is easily discoverable*  then the source or Dockerfile does not have to live in this repo.

*: examples: `[docker.io/library/]tomcat`, `quay.io/coreos/etcd`, or `gcr.io/google_containers/echoserver`

**Comment by chrislovecnm** [comment]
Can get opinion that into the docs?  PR and discuss officially?
