### ISSUE TITLE
Cassandra GetEndPoints fails with return value Java_com_sun_jna_Native_getStringBytes

### ISSUE THREAD

**Issue by rroopreddy** [kubernetes/examples#287]
I seem to get 2 out of 3 cassandra nodes start but the 3rd one fails with the following. Seems to be a problem with the 'main.go' code. Any help is appreciated

```
INFO  17:32:35 get endpoint params: default, cassandra, cassandra-0.cassandra.default.svc.cluster.local
**INFO  17:32:35 cassandra endpoint data: Java_com_sun_jna_Native_getStringBytes**
ERROR 17:32:35 unexpected error building cassandra seeds: Unexpected character ('J' (code 74)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@5fd4f8f5; line: 1, column: 2]
Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: The seed provider lists no seeds.
The seed provider lists no seeds.
ERROR 17:32:35 Exception encountered during startup: The seed provider lists no seeds.
```

other two have the correct data

```
INFO  17:30:57 get endpoint params: default, cassandra, cassandra-0.cassandra.default.svc.cluster.local
**INFO  17:30:58 cassandra endpoint data: {"ips":["cassandra-0.cassandra.default.svc.cluster.local"]}**
```

I instrumented the 'KubernetesSeedProvider.java' with two additional 'logger.info' lines to get this data

``` java
logger.info("get endpoint params: " + namespace + ", " + service + ", " + initialSeeds);
String data = go.GetEndpoints(namespace, service, initialSeeds);
logger.info("cassandra endpoint data: " + data);
```

**Comment by asalian** [comment]
We have also run into this issue (among many other issues such as missing packages required by Cassandra from the base image k8s.gcr.io/debian-base-amd64:0.3 that are not included in the build.sh file) . Having said this this issue happens in the interface between GO and Java using JNIA  The CString's memory allocation is freed before the Java has time to read it and java fails during string get bytes read call.  you can see this by commenting the following line in main.go.  Then the 3rd and 4th cassandra pods should run properly
      //defer C.free(unsafe.Pointer(rc))

 Obviously using defer (which defers the memory allocation to the end of call in the current code) is not going to solve this issue.  Also we can't leave this line commented. The memory needs to be released otherwise we will have a memory leak

This issue can be solved by freeing the memory from java side once the java is done reading the seeds string (which has a json format). 

Also there are many unused code on the java JNA side that is complicating troubleshooting this issue.  My recommendation of to remove this code and simplify the GoInterface on the java side (BTW there are many instances of unused code all over the place, ex: look at   Integer seedSize inside the provider java class)

1- Content  of GoInterface.java should be as following:
/***** Start of File ********/
package io.k8s.cassandra;

import java.util.Arrays;
import java.util.List;

import com.sun.jna.Library;
import com.sun.jna.Pointer;

public interface GoInterface extends Library {
        public Pointer GetEndpoints(String namespace, String service, String seeds);
        public void FreeCString (Pointer cString);**

}
/***** End of File ********/

2- Also "KubernetesSeedProvider.java needs to change where we call the GetEndPoints with the following (note that . you need to import the pointer in the beginning of java file (import com.sun.jna.Pointer;)


                Pointer seedsPointer = go.GetEndpoints(namespace, service, initialSeeds);
                String data = seedsPointer.getString(0);

                //cleanup allocated memory in the GO/C program
                go.FreeCString(endPointPointer);

3- Finally on the GO side we need to comment the following call:
      //defer C.free(unsafe.Pointer(rc))
and add the following additional method for java to free up the memory (make sure you copy export line below):

//export FreeCString 
func FreeCString (buf *C.char) {
	log.Printf("Freeing memory for String: "+C.GoString(buf))
        C.free(unsafe.Pointer(buf))
        log.Printf("Mem free completed inside Native GO generated library for seed string.\n")
        }

We can make files available to you if you are interested.  Good luck
