### ISSUE TITLE
Should minio service be a Deployment or a Statefulset?

### ISSUE THREAD

**Issue by tiendatiowa** [kubernetes/examples#463]
In the example [manifest](https://github.com/kubernetes/examples/blob/master/staging/storage/minio/README.md#step-2-create-minio-deployment), the service is deployed as a Deployment and a ReadWriteOnce PVC. But a Deployment with a ReadWriteOnce PVC is not recommended per K8S [doc](https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#deployments_vs_statefulsets):

> Even Deployments with one replica using ReadWriteOnce volume are not recommended. This is because the default Deployment strategy creates a second Pod before bringing down the first Pod on a recreate. The Deployment may fail in deadlock as the second Pod can't start because the ReadWriteOnce volume is already in use, and the first Pod won't be removed because the second Pod has not yet started. Instead, use a StatefulSet with ReadWriteOnce volumes.

So the question is: is the use of Deployment on purpose? Or should the example be updated to use Statefulset?

**Comment by yrs147** [comment]
It is generally not recommended to use a Deployment with a ReadWriteOnce PVC because, as you mentioned, the default Deployment strategy involves creating a new Pod before tearing down the old one, which can lead to a deadlock if the new Pod is unable to start due to the ReadWriteOnce volume being in use.

A StatefulSet, on the other hand, is designed to handle persistent storage more gracefully and is a better choice when using ReadWriteOnce volumes. It ensures that each Pod is created and terminated in a specific order, which helps to avoid the potential deadlock scenario that can occur with Deployments.

That being said, it is possible to use a Deployment with a ReadWriteOnce PVC if you are willing to accept the risks and are prepared to handle potential failures. However, it is generally recommended to use a StatefulSet instead in order to avoid these issues.

In the example you mentioned, it is possible that the use of a Deployment with a ReadWriteOnce PVC was intentional in order to illustrate a specific scenario or to demonstrate how to handle persistent storage in a Deployment. However, if the goal of the example is to provide a recommended practice for using persistent storage with Kubernetes, it may be worth considering updating the example to use a StatefulSet instead.
